## CVE & CWE Mapping dataset
This file will pull the dataset from https://huggingface.co/datasets/zefang-liu/cve-and-cwe-mapping-dataset/ and use the data gathered through the scrapers to make it more complete and remove any noise from the final dataset.

### Requirements

In [ ]:
!pip install pandas
!pip install -q huggingface_hub python-dotenv

Requirement already satisfied: pandas in /home/regularpooria/Projects/CWE_CVE_Mapping/venv/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /home/regularpooria/Projects/CWE_CVE_Mapping/venv/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/regularpooria/Projects/CWE_CVE_Mapping/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/regularpooria/Projects/CWE_CVE_Mapping/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Gather data

In [64]:
import pandas as pd
import json
import re

This is the original dataset we're going to modify

In [65]:
df = pd.read_csv("hf://datasets/zefang-liu/cve-and-cwe-mapping-dataset/Global_Dataset.csv")
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,DESCRIPTION,CWE-ID
0,1,CVE-1999-0001,NaN,5.0,MEDIUM,ip_input.c in BSD-derived TCP/IP implementatio...,CWE-20
1,2,CVE-1999-0002,NaN,10.0,HIGH,Buffer overflow in NFS mountd gives root acces...,CWE-119
2,3,CVE-1999-0003,NaN,10.0,HIGH,Execute commands as root via buffer overflow i...,NVD-CWE-Other
3,4,CVE-1999-0004,NaN,5.0,MEDIUM,"MIME buffer overflow in email clients, e.g. So...",NVD-CWE-Other
4,5,CVE-1999-0005,NaN,10.0,HIGH,Arbitrary command execution via IMAP buffer ov...,NVD-CWE-Other

This is the data where we scraped from CWE's websites

In [66]:
# == KAGGLE/COLAB ==

# !git clone https://github.com/regularpooria/CWE_CVE_Mapping # Kaggle
# BASE_DIR = "./CWE_CVE_Mapping" # Kaggle

# == LOCAL ==
BASE_DIR = "../" # Local
with open(f"{BASE_DIR}/scrapers/scraped_data/CWE_SOFTWARE.json", "r", encoding="utf-8") as f:
    CWE = json.load(f)
    
list_of_CWEs = set()
for category_id, category in CWE.items():
    list_of_CWEs.add(category_id)
    list_of_CWEs |= set(list(category["children"].keys()))

## Merging the 2 data sources

In [67]:
# Removing any ambiguous cases.

values_to_remove = ['NVD-CWE-Other', 'NVD-CWE-noinfo']
df = df[~df['CWE-ID'].isin(values_to_remove)]
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,DESCRIPTION,CWE-ID
0,1,CVE-1999-0001,NaN,5.0,MEDIUM,ip_input.c in BSD-derived TCP/IP implementatio...,CWE-20
1,2,CVE-1999-0002,NaN,10.0,HIGH,Buffer overflow in NFS mountd gives root acces...,CWE-119
6,7,CVE-1999-0007,NaN,5.0,MEDIUM,Information from SSL-encrypted sessions via PK...,CWE-327
25,26,CVE-1999-0027,NaN,7.2,HIGH,root privileges via buffer overflow in eject c...,CWE-119
176,177,CVE-1999-0179,NaN,5.0,MEDIUM,Windows NT crashes or locks up when a Samba cl...,CWE-17

In [68]:
# Extract the year
def extract_year(CVE_ID):
    return int(CVE_ID.split("-")[1])

df["YEAR"] = df["CVE-ID"].apply(extract_year)
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,DESCRIPTION,CWE-ID,YEAR
0,1,CVE-1999-0001,NaN,5.0,MEDIUM,ip_input.c in BSD-derived TCP/IP implementatio...,CWE-20,1999
1,2,CVE-1999-0002,NaN,10.0,HIGH,Buffer overflow in NFS mountd gives root acces...,CWE-119,1999
6,7,CVE-1999-0007,NaN,5.0,MEDIUM,Information from SSL-encrypted sessions via PK...,CWE-327,1999
25,26,CVE-1999-0027,NaN,7.2,HIGH,root privileges via buffer overflow in eject c...,CWE-119,1999
176,177,CVE-1999-0179,NaN,5.0,MEDIUM,Windows NT crashes or locks up when a Samba cl...,CWE-17,1999

In [69]:
# Check to see if they are in CWE699 (SOFTWARE)
def is_in_CWE699(CWE_ID):
    id = CWE_ID.split("-")[-1]
    return id in list_of_CWEs

df["IS-IN-CWE699"] = df["CWE-ID"].apply(is_in_CWE699)
df = df[~df['IS-IN-CWE699'] == False]
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,DESCRIPTION,CWE-ID,YEAR,IS-IN-CWE699
195,196,CVE-1999-0199,9.8,7.5,CRITICAL,manual/search.texi in the GNU C Library (aka g...,CWE-252,1999,True
222,223,CVE-1999-0226,NaN,10.0,HIGH,Windows NT TCP/IP processes fragmented IP pack...,CWE-19,1999,True
279,280,CVE-1999-0284,NaN,7.5,HIGH,Denial of service to NT mail servers including...,CWE-120,1999,True
380,381,CVE-1999-0385,NaN,10.0,HIGH,The LDAP bind function in Exchange 5.5 has a b...,CWE-120,1999,True
382,383,CVE-1999-0387,NaN,7.8,HIGH,A legacy credential caching mechanism used in ...,CWE-255,1999,True

In [70]:
df = df.rename(columns={"DESCRIPTION": "CVE-DESCRIPTION"})
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,CVE-DESCRIPTION,CWE-ID,YEAR,IS-IN-CWE699
195,196,CVE-1999-0199,9.8,7.5,CRITICAL,manual/search.texi in the GNU C Library (aka g...,CWE-252,1999,True
222,223,CVE-1999-0226,NaN,10.0,HIGH,Windows NT TCP/IP processes fragmented IP pack...,CWE-19,1999,True
279,280,CVE-1999-0284,NaN,7.5,HIGH,Denial of service to NT mail servers including...,CWE-120,1999,True
380,381,CVE-1999-0385,NaN,10.0,HIGH,The LDAP bind function in Exchange 5.5 has a b...,CWE-120,1999,True
382,383,CVE-1999-0387,NaN,7.8,HIGH,A legacy credential caching mechanism used in ...,CWE-255,1999,True

In [71]:
# Children to parent mapping

children_to_parent = {}
for category_id, category in CWE.items():
    for child_id, child in category["children"].items():
        child_id = str(child_id)
        item_to_add = str(category_id)
        item_to_add = (f"CWE-{category_id}", category["summary"])
        if child_id in children_to_parent:
            children_to_parent[child_id]["parents"].append(item_to_add)  
        else:
            children_to_parent[child_id] = child
            children_to_parent[child_id]["parents"] = [item_to_add]

In [72]:
def get_parent_id(CWE_ID):
    id = CWE_ID.split("-")[-1] # "CWE-199" -> "199"
    if id not in children_to_parent:
        return pd.NA
    
    return children_to_parent[id]["parents"]

df["PARENTS"] = df["CWE-ID"].apply(get_parent_id)
df = df[~df["PARENTS"].isna()]
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,CVE-DESCRIPTION,CWE-ID,YEAR,IS-IN-CWE699,PARENTS
195,196,CVE-1999-0199,9.8,7.5,CRITICAL,manual/search.texi in the GNU C Library (aka g...,CWE-252,1999,True,"[(CWE-389, This category includes weaknesses t..."
279,280,CVE-1999-0284,NaN,7.5,HIGH,Denial of service to NT mail servers including...,CWE-120,1999,True,"[(CWE-1218, Weaknesses in this category are re..."
380,381,CVE-1999-0385,NaN,10.0,HIGH,The LDAP bind function in Exchange 5.5 has a b...,CWE-120,1999,True,"[(CWE-1218, Weaknesses in this category are re..."
485,486,CVE-1999-0491,NaN,4.6,MEDIUM,The prompt parsing in bash allows a local user...,CWE-94,1999,True,"[(CWE-137, Weaknesses in this category are rel..."
502,503,CVE-1999-0509,NaN,10.0,HIGH,"Perl, sh, csh, or other shell interpreters are...",CWE-94,1999,True,"[(CWE-137, Weaknesses in this category are rel..."

In [84]:
def get_CWE_description(CWE_ID):
    id = CWE_ID.split("-")[-1] # "CWE-199" -> "199"
    return children_to_parent[id]["description"]

df["CWE-DESCRIPTION"] = df["CWE-ID"].apply(get_CWE_description)
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,CVE-DESCRIPTION,CWE-ID,YEAR,IS-IN-CWE699,PARENTS,CWE-DESCRIPTION,CVE-DESCRIPTION-NORMALIZED
195,196,CVE-1999-0199,9.8,7.5,CRITICAL,manual/search.texi in the GNU C Library (aka g...,CWE-252,1999,True,"[(CWE-389, This category includes weaknesses t...",The product does not check the return value fr...,manual/search.texi in the C Library before lac...
279,280,CVE-1999-0284,NaN,7.5,HIGH,Denial of service to NT mail servers including...,CWE-120,1999,True,"[(CWE-1218, Weaknesses in this category are re...",The product copies an input buffer to an outpu...,"Denial of service to mail servers including,, ..."
380,381,CVE-1999-0385,NaN,10.0,HIGH,The LDAP bind function in Exchange 5.5 has a b...,CWE-120,1999,True,"[(CWE-1218, Weaknesses in this category are re...",The product copies an input buffer to an outpu...,The bind function in has a buffer overflow tha...
485,486,CVE-1999-0491,NaN,4.6,MEDIUM,The prompt parsing in bash allows a local user...,CWE-94,1999,True,"[(CWE-137, Weaknesses in this category are rel...",The product constructs all or part of a code s...,The prompt parsing in bash allows a local user...
502,503,CVE-1999-0509,NaN,10.0,HIGH,"Perl, sh, csh, or other shell interpreters are...",CWE-94,1999,True,"[(CWE-137, Weaknesses in this category are rel...",The product constructs all or part of a code s...,"Perl, sh, csh, or other shell interpreters are..."

## Post processing on the data

In [ ]:
from utils import remove_capital_words, remove_parentheses

In [97]:
tmp = "Apache Log4j2 2.0-beta9 through 2.12.1 and 2.13.0 through 2.15.0 JNDI (user patch is recommended) features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled. From log4j 2.15.0, this behavior has been disabled by default. From version 2.16.0, this functionality has been completely removed. Note that this vulnerability is specific to log4j-core and does not affect log4net, log4cxx, or other Apache Logging Services projects"
print(tmp)
print(remove_capital_words(remove_parentheses(tmp)))

Apache Log4j2 2.0-beta9 through 2.12.1 and 2.13.0 through 2.15.0 JNDI (user patch is recommended) features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled. From log4j 2.15.0, this behavior has been disabled by default. From version 2.16.0, this functionality has been completely removed. Note that this vulnerability is specific to log4j-core and does not affect log4net, log4cxx, or other Apache Logging Services projects
Apache through and through JNDI features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled. From, this behavior has been disabled by default. From version, this functionality has been completely removed. Note that this vulnerability is specific to and does not affect,, or other projects

In [94]:
removed_words

[('Ipswitch',
  'Denial of service to NT mail servers including Ipswitch, Mdaemon, and Exchange through a buffer overflow in the SMTP HELO command'),
 ('Mdaemon',
  'Denial of service to NT mail servers including Ipswitch, Mdaemon, and Exchange through a buffer overflow in the SMTP HELO command'),
 ('Exchange',
  'Denial of service to NT mail servers including Ipswitch, Mdaemon, and Exchange through a buffer overflow in the SMTP HELO command'),
 ('Exchange',
  'The LDAP bind function in Exchange 5.5 has a buffer overflow that allows a remote attacker to conduct a denial of service or execute commands'),
 ('Explorer',
  'Internet Explorer 5.0 and 5.01 allows remote attackers to modify or execute files via the Import/Export Favorites feature, aka the "ImportExportFavorites" vulnerability'),
 ('ImportExportFavorites',
  'Internet Explorer 5.0 and 5.01 allows remote attackers to modify or execute files via the Import/Export Favorites feature, aka the "ImportExportFavorites" vulnerability'),
 ('Excel',
  'Microsoft Excel does not warn a user when a macro is present in a Symbolic Link  format file'),
 ('Symbolic',
  'Microsoft Excel does not warn a user when a macro is present in a Symbolic Link  format file'),
 ('Link',
  'Microsoft Excel does not warn a user when a macro is present in a Symbolic Link  format file'),
 ('Internet',
  'The "download behavior" in Internet Explorer 5 allows remote attackers to read arbitrary files via a server-side redirect'),
 ('Explorer',
  'The "download behavior" in Internet Explorer 5 allows remote attackers to read arbitrary files via a server-side redirect'),
 ('Internet',
  'Buffer overflow in Internet Mail Service  for Microsoft Exchange 5.5 and 5.0 allows remote attackers to conduct a denial of service via AUTH or AUTHINFO commands'),
 ('Mail',
  'Buffer overflow in Internet Mail Service  for Microsoft Exchange 5.5 and 5.0 allows remote attackers to conduct a denial of service via AUTH or AUTHINFO commands'),
 ('Microsoft',
  'Buffer overflow in Internet Mail Service  for Microsoft Exchange 5.5 and 5.0 allows remote attackers to conduct a denial of service via AUTH or AUTHINFO commands'),
 ('Exchange',
  'Buffer overflow in Internet Mail Service  for Microsoft Exchange 5.5 and 5.0 allows remote attackers to conduct a denial of service via AUTH or AUTHINFO commands'),
 ('Explorer',
  'Internet Explorer 5.01 and earlier allows a remote attacker to create a reference to a client window and use a server-side redirect to access local files via that window, aka "Server-side Page Reference Redirect."'),
 ('Page',
  'Internet Explorer 5.01 and earlier allows a remote attacker to create a reference to a client window and use a server-side redirect to access local files via that window, aka "Server-side Page Reference Redirect."'),
 ('Apache',
  'Multiple buffer overflows in smbvalid/smbval SMB authentication library, as used in Apache::AuthenSmb and possibly other modules, allows remote attackers to execute arbitrary commands via  a long username,  a long password, and  other unspecified methods'),
 ('AuthenSmb',
  'Multiple buffer overflows in smbvalid/smbval SMB authentication library, as used in Apache::AuthenSmb and possibly other modules, allows remote attackers to execute arbitrary commands via  a long username,  a long password, and  other unspecified methods'),
 ('Internet',
  'Windows Internet Naming Service  allows remote attackers to cause a denial of service  or steal credentials via a 1Ch registration that causes WINS to change the domain controller to point to a malicious server'),
 ('Naming',
  'Windows Internet Naming Service  allows remote attackers to cause a denial of service  or steal credentials via a 1Ch registration that causes WINS to change the domain controller to point to a malicious server'),
 ('Windows',
  'NOTE: this problem may be limited when Windows 95/98 clients are used, or if the primary domain controller becomes unavailable'),
 ('Autorun',
  'Windows NT Autorun executes the autorun.inf file on non-removable media, which allows local attackers to specify an alternate program to execute when other users access a drive'),
 ('Red',
  'DiskCheck script diskcheck.pl in Red Hat Linux 6.2 allows local users to create or overwrite arbitrary files via a symlink attack on a temporary file'),
 ('Hat',
  'DiskCheck script diskcheck.pl in Red Hat Linux 6.2 allows local users to create or overwrite arbitrary files via a symlink attack on a temporary file'),
 ('Linux',
  'DiskCheck script diskcheck.pl in Red Hat Linux 6.2 allows local users to create or overwrite arbitrary files via a symlink attack on a temporary file'),
 ('Microsoft', 'The installation of Microsoft Exchange 2000 before Rev'),
 ('Exchange', 'The installation of Microsoft Exchange 2000 before Rev'),
 ('Rev', 'The installation of Microsoft Exchange 2000 before Rev'),
 ('Exchange',
  'A creates a user account with a known password, which could allow attackers to gain privileges, aka the "Exchange User Account" vulnerability'),
 ('User',
  'A creates a user account with a known password, which could allow attackers to gain privileges, aka the "Exchange User Account" vulnerability'),
 ('Account',
  'A creates a user account with a known password, which could allow attackers to gain privileges, aka the "Exchange User Account" vulnerability'),
 ('Apache',
  'Cross site scripting vulnerabilities in Apache 1.3.0 through 1.3.11 allow remote attackers to execute script as other web site visitors via  the printenv CGI , which does not encode its output,  pages generated by the ap_send_error_response function such as a default 404, which does not add an explicit charset, or  various messages that are generated by certain Apache modules or core code'),
 ('Apache',
  'Cross site scripting vulnerabilities in Apache 1.3.0 through 1.3.11 allow remote attackers to execute script as other web site visitors via  the printenv CGI , which does not encode its output,  pages generated by the ap_send_error_response function such as a default 404, which does not add an explicit charset, or  various messages that are generated by certain Apache modules or core code'),
 ('Internet',
  'NOTE: the printenv issue might still exist for web browsers that can render text/plain content types as HTML, such as Internet Explorer, but CVE regards this as a design limitation of those browsers, not Apache'),
 ('Explorer',
  'NOTE: the printenv issue might still exist for web browsers that can render text/plain content types as HTML, such as Internet Explorer, but CVE regards this as a design limitation of those browsers, not Apache'),
 ('Apache',
  'NOTE: the printenv issue might still exist for web browsers that can render text/plain content types as HTML, such as Internet Explorer, but CVE regards this as a design limitation of those browsers, not Apache'),
 ('Serv',
  'Directory traversal vulnerability in FTP Serv-U before 2.5i allows remote attackers to escape the FTP root and read arbitrary files by appending a string such as "/..%20." to a CD command, a variant of a'),
 ('Apache',
  'htpasswd and htdigest in Apache 2.0a9, 1.3.14, and others allows local users to overwrite arbitrary files via a symlink attack'),
 ('JServer',
  'Bajie HTTP JServer 0.78, and other versions before 0.80, allows remote attackers to execute arbitrary commands via shell metacharacters in an HTTP request for a CGI program that does not exist'),
 ('Bajie',
  'UploadServlet in Bajie HTTP JServer 0.78, and possibly other versions before 0.80, allows remote attackers to execute arbitrary commands by calling the servlet to upload a program, then using a'),
 ('JServer',
  'UploadServlet in Bajie HTTP JServer 0.78, and possibly other versions before 0.80, allows remote attackers to execute arbitrary commands by calling the servlet to upload a program, then using a'),
 ('Outlook',
  "An interaction between the Outlook Web Access  service in Microsoft Exchange 2000 Server and Internet Explorer allows attackers to execute malicious script code against a user's mailbox via a message attachment that contains HTML code, which is executed automatically"),
 ('Web',
  "An interaction between the Outlook Web Access  service in Microsoft Exchange 2000 Server and Internet Explorer allows attackers to execute malicious script code against a user's mailbox via a message attachment that contains HTML code, which is executed automatically"),
 ('Microsoft',
  "An interaction between the Outlook Web Access  service in Microsoft Exchange 2000 Server and Internet Explorer allows attackers to execute malicious script code against a user's mailbox via a message attachment that contains HTML code, which is executed automatically"),
 ('Exchange',
  "An interaction between the Outlook Web Access  service in Microsoft Exchange 2000 Server and Internet Explorer allows attackers to execute malicious script code against a user's mailbox via a message attachment that contains HTML code, which is executed automatically"),
 ('Internet',
  "An interaction between the Outlook Web Access  service in Microsoft Exchange 2000 Server and Internet Explorer allows attackers to execute malicious script code against a user's mailbox via a message attachment that contains HTML code, which is executed automatically"),
 ('Explorer',
  "An interaction between the Outlook Web Access  service in Microsoft Exchange 2000 Server and Internet Explorer allows attackers to execute malicious script code against a user's mailbox via a message attachment that contains HTML code, which is executed automatically"),
 ('Cosmicperl',
  'Directory traversal vulnerability in cosmicpro.cgi in Cosmicperl Directory Pro 2.0 allows remote attackers to gain sensitive information via a'),
 ('Pro',
  'Directory traversal vulnerability in cosmicpro.cgi in Cosmicperl Directory Pro 2.0 allows remote attackers to gain sensitive information via a'),
 ('Apache',
  'The default installation of Apache before 1.3.19 allows remote attackers to list directories instead of the multiview index.html file via an HTTP request for a path that contains many /  characters, which causes the path to be mishandled by  mod_negotiation,  mod_dir, or  mod_autoindex'),
 ('Norton',
  "The default configuration of Norton AntiVirus for Microsoft Exchange 2000 2.x allows remote attackers to identify the recipient's INBOX file path by sending an email with an attachment containing malicious content, which includes the path in the rejection notice"),
 ('AntiVirus',
  "The default configuration of Norton AntiVirus for Microsoft Exchange 2000 2.x allows remote attackers to identify the recipient's INBOX file path by sending an email with an attachment containing malicious content, which includes the path in the rejection notice"),
 ('Microsoft',
  "The default configuration of Norton AntiVirus for Microsoft Exchange 2000 2.x allows remote attackers to identify the recipient's INBOX file path by sending an email with an attachment containing malicious content, which includes the path in the rejection notice"),
 ('Exchange',
  "The default configuration of Norton AntiVirus for Microsoft Exchange 2000 2.x allows remote attackers to identify the recipient's INBOX file path by sending an email with an attachment containing malicious content, which includes the path in the rejection notice"),
 ('Cherokee',
  'Directory traversal vulnerability in Cherokee Web Server allows remote attackers to read arbitrary files via a'),
 ('Web',
  'Directory traversal vulnerability in Cherokee Web Server allows remote attackers to read arbitrary files via a'),
 ('SimpleServer',
  'Directory traversal vulnerability in SimpleServer:WWW 1.13 and earlier allows remote attackers to execute arbitrary programs via encoded ../  sequences in a request to the cgi-bin/ directory, a different vulnerability than CVE-2000-0664'),
 ('Microsoft',
  'SMTP service in  Microsoft Windows 2000 and  Internet Mail Connector  in Exchange Server 5.5 does not properly handle responses to NTLM authentication, which allows remote attackers to perform mail relaying via an SMTP AUTH command using null session credentials'),
 ('Windows',
  'SMTP service in  Microsoft Windows 2000 and  Internet Mail Connector  in Exchange Server 5.5 does not properly handle responses to NTLM authentication, which allows remote attackers to perform mail relaying via an SMTP AUTH command using null session credentials'),
 ('Internet',
  'SMTP service in  Microsoft Windows 2000 and  Internet Mail Connector  in Exchange Server 5.5 does not properly handle responses to NTLM authentication, which allows remote attackers to perform mail relaying via an SMTP AUTH command using null session credentials'),
 ('Mail',
  'SMTP service in  Microsoft Windows 2000 and  Internet Mail Connector  in Exchange Server 5.5 does not properly handle responses to NTLM authentication, which allows remote attackers to perform mail relaying via an SMTP AUTH command using null session credentials'),
 ('Connector',
  'SMTP service in  Microsoft Windows 2000 and  Internet Mail Connector  in Exchange Server 5.5 does not properly handle responses to NTLM authentication, which allows remote attackers to perform mail relaying via an SMTP AUTH command using null session credentials'),
 ('Exchange',
  'SMTP service in  Microsoft Windows 2000 and  Internet Mail Connector  in Exchange Server 5.5 does not properly handle responses to NTLM authentication, which allows remote attackers to perform mail relaying via an SMTP AUTH command using null session credentials'),
 ('Cisco',
  'Format string vulnerability in the administration function in Cisco Secure Access Control Server  for Windows, 2.6.x and earlier and 3.x through 3.01 , allows remote attackers to crash the CSADMIN  module only  or execute arbitrary code via format strings in the URL to port 2002'),
 ('Secure',
  'Format string vulnerability in the administration function in Cisco Secure Access Control Server  for Windows, 2.6.x and earlier and 3.x through 3.01 , allows remote attackers to crash the CSADMIN  module only  or execute arbitrary code via format strings in the URL to port 2002'),
 ('Windows',
  'Format string vulnerability in the administration function in Cisco Secure Access Control Server  for Windows, 2.6.x and earlier and 3.x through 3.01 , allows remote attackers to crash the CSADMIN  module only  or execute arbitrary code via format strings in the URL to port 2002'),
 ('Internet',
  "Buffer overflow in Internet Mail Connector  for Microsoft Exchange Server 5.5 allows remote attackers to execute arbitrary code via an EHLO request from a system with a long name as obtained through a reverse DNS lookup, which triggers the overflow in IMC's hello response"),
 ('Mail',
  "Buffer overflow in Internet Mail Connector  for Microsoft Exchange Server 5.5 allows remote attackers to execute arbitrary code via an EHLO request from a system with a long name as obtained through a reverse DNS lookup, which triggers the overflow in IMC's hello response"),
 ('Connector',
  "Buffer overflow in Internet Mail Connector  for Microsoft Exchange Server 5.5 allows remote attackers to execute arbitrary code via an EHLO request from a system with a long name as obtained through a reverse DNS lookup, which triggers the overflow in IMC's hello response"),
 ('Microsoft',
  "Buffer overflow in Internet Mail Connector  for Microsoft Exchange Server 5.5 allows remote attackers to execute arbitrary code via an EHLO request from a system with a long name as obtained through a reverse DNS lookup, which triggers the overflow in IMC's hello response"),
 ('Exchange',
  "Buffer overflow in Internet Mail Connector  for Microsoft Exchange Server 5.5 allows remote attackers to execute arbitrary code via an EHLO request from a system with a long name as obtained through a reverse DNS lookup, which triggers the overflow in IMC's hello response"),
 ('Verity',
  'Cross-site scripting  vulnerability in Verity Search97 allows remote attackers to insert arbitrary web content and steal sensitive information from other clients, possibly due to certain error messages from template pages that use the  vformat or  vfilter functions'),
 ('Search97',
  'Cross-site scripting  vulnerability in Verity Search97 allows remote attackers to insert arbitrary web content and steal sensitive information from other clients, possibly due to certain error messages from template pages that use the  vformat or  vfilter functions'),
 ('Macromedia',
  'Cross-site scripting vulnerability  in the missing template handler in Macromedia ColdFusion MX allows remote attackers to execute arbitrary script as other users by injecting script into the HTTP request for the name of a template, which is not filtered in the resulting 404 error message'),
 ('ColdFusion',
  'Cross-site scripting vulnerability  in the missing template handler in Macromedia ColdFusion MX allows remote attackers to execute arbitrary script as other users by injecting script into the HTTP request for the name of a template, which is not filtered in the resulting 404 error message'),
 ('Monkey',
  'Cross-site scripting  vulnerability in Monkey 0.5.0 allows remote attackers to inject arbitrary web script or HTML via  the URL or  a parameter to test2.pl'),
 ('Subject',
  'Cross-site scripting  vulnerability in kmMail 1.0, 1.0a, and 1.0b allows remote attackers to inject arbitrary web script or HTML via  javascript in onmouseover or other attributes in "safe" HTML tags such as the "b" tag, or  the Subject field'),
 ('Monkey',
  'Directory traversal vulnerability in Monkey HTTP Daemon 0.1.4 allows remote attackers to read arbitrary files via'),
 ('Daemon',
  'Directory traversal vulnerability in Monkey HTTP Daemon 0.1.4 allows remote attackers to read arbitrary files via'),
 ('Sapio', 'Directory traversal vulnerability in Sapio Design Ltd'),
 ('Design', 'Directory traversal vulnerability in Sapio Design Ltd'),
 ('Ltd', 'Directory traversal vulnerability in Sapio Design Ltd'),
 ('Ikonboard',
  'Cross-site scripting  vulnerability in Ikonboard 3.1.1 allows remote attackers to inject arbitrary web script or HTML via a private message with a javascript: URL in the IMG tag, in which the URL ends in a ".gif" or ".jpg" string, a variant of CVE-2002-0328'),
 ('Ikonboard',
  'Cross-site scripting  vulnerability in Ikonboard 3.1.1 allows remote attackers to inject arbitrary web script or HTML via  a javascript: URL in a photo URL or  an X-Forwarded-For: header'),
 ('Forwarded',
  'Cross-site scripting  vulnerability in Ikonboard 3.1.1 allows remote attackers to inject arbitrary web script or HTML via  a javascript: URL in a photo URL or  an X-Forwarded-For: header'),
 ('For',
  'Cross-site scripting  vulnerability in Ikonboard 3.1.1 allows remote attackers to inject arbitrary web script or HTML via  a javascript: URL in a photo URL or  an X-Forwarded-For: header'),
 ('Enceladus',
  'Directory traversal vulnerability in Enceladus Server Suite 3.9 allows remote attackers to list arbitrary directories and possibly cause a denial of service via "@"  characters in a CD  command, such as  "@/....\\",  "@@@/..c:\\", or  "@/..@/.."'),
 ('Suite',
  'Directory traversal vulnerability in Enceladus Server Suite 3.9 allows remote attackers to list arbitrary directories and possibly cause a denial of service via "@"  characters in a CD  command, such as  "@/....\\",  "@@@/..c:\\", or  "@/..@/.."'),
 ('Kunani',
  'Directory traversal vulnerability in the Kunani ODBC FTP Server 1.0.10 allows remote attackers to read arbitrary files via a "..\\"  in a GET request'),
 ('MyServer',
  'Directory traversal vulnerability in MyServer 0.11 and 0.2 allows remote attackers to read arbitrary files via a ".."  in an HTTP GET request'),
 ('VisNetic',

In [95]:
df.head(5)

,ID,CVE-ID,CVSS-V3,CVSS-V2,SEVERITY,CVE-DESCRIPTION,CWE-ID,YEAR,IS-IN-CWE699,PARENTS,CWE-DESCRIPTION,CVE-DESCRIPTION-NORMALIZED
195,196,CVE-1999-0199,9.8,7.5,CRITICAL,manual/search.texi in the GNU C Library (aka g...,CWE-252,1999,True,"[(CWE-389, This category includes weaknesses t...",The product does not check the return value fr...,manual/search.texi in the GNU C Library before...
279,280,CVE-1999-0284,NaN,7.5,HIGH,Denial of service to NT mail servers including...,CWE-120,1999,True,"[(CWE-1218, Weaknesses in this category are re...",The product copies an input buffer to an outpu...,Denial of service to NT mail servers including...
380,381,CVE-1999-0385,NaN,10.0,HIGH,The LDAP bind function in Exchange 5.5 has a b...,CWE-120,1999,True,"[(CWE-1218, Weaknesses in this category are re...",The product copies an input buffer to an outpu...,The LDAP bind function in has a buffer overflo...
485,486,CVE-1999-0491,NaN,4.6,MEDIUM,The prompt parsing in bash allows a local user...,CWE-94,1999,True,"[(CWE-137, Weaknesses in this category are rel...",The product constructs all or part of a code s...,The prompt parsing in bash allows a local user...
502,503,CVE-1999-0509,NaN,10.0,HIGH,"Perl, sh, csh, or other shell interpreters are...",CWE-94,1999,True,"[(CWE-137, Weaknesses in this category are rel...",The product constructs all or part of a code s...,"Perl, sh, csh, or other shell interpreters are..."

In [98]:
# Save the final dataset locally and commit it to the Hugging Face dataset repository.
import os
from pathlib import Path
from dotenv import load_dotenv
from huggingface_hub import HfApi

load_dotenv()
HF_REPO_ID = os.environ.get(
    "HF_DATASET_REPO_ID",
    "regularpooria/CVE_CWE_Software_Mapping_Dataset",
)

UPLOAD_DIR = Path("hf_upload")
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
DATASET_PATH = UPLOAD_DIR / "Global_Dataset.csv"
df.to_csv(DATASET_PATH, index=False)

api = HfApi(token=os.environ.get("HF_TOKEN"))
commit_url = api.upload_folder(
    folder_path=str(UPLOAD_DIR),
    repo_id=HF_REPO_ID,
    repo_type="dataset",
    commit_message="Update CVE-CWE Software Weakness Mapping Dataset",
)

print(f"Saved {len(df):,} rows to {DATASET_PATH}")
print(f"Committed dataset and dataset card to {commit_url}")

Saved 60,897 rows to hf_upload/Global_Dataset.csv
Committed dataset and dataset card to https://huggingface.co/datasets/regularpooria/CVE_CWE_Software_Mapping_Dataset/commit/82f0569034f6fecefa901178f26a7014bab33760